% Each new term in the Fibonacci sequence is generated by adding the 
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not 
% exceed four million, find the sum of the even-valued terms.

limit = 4e6;

term1 = 1;
term2 = 2;
total = 2;

term3 = term1 + term2;
while term3 < limit
   if mod(term3, 2) == 0
       total = total + term3;
   end
   
   term1 = term2;
   term2 = term3;
   term3 = term1 + term2;
end

disp(total);